version: '3.8'

services:
  app:
    image: openjdk:17-alpine
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
    volumes:
      - ./logs:/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
