# Use the base image of OpenJDK 21 with the slim version
FROM openjdk:21-jdk-slim

# Create a directory for the application
WORKDIR /app

# Copy the JAR file generated by Maven into the working directory
COPY target/SpaceshipW2M-0.0.1-SNAPSHOT.jar /app/spaceship-api.jar

# Expose the port in the container
EXPOSE 8080 5005

# Define the command to run the Spring Boot application
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app/spaceship-api.jar"]
